name: Metrics
on:
  schedule: [{cron: "0 */4 * * *"}]
  push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.TOKEN }}

          # Options
          user: alixcpp
          template: classic
          base: activity, community, metadata
          config_timezone: Asia/Jakarta
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage             # Additionally display total bytes size and percentage
          plugin_languages_threshold: 2%                               # Hides all languages less than 2%
          plugin_tweets: no
          plugin_tweets_limit: 4
          plugin_tweets_user: alixcpps
          plugin_stars: yes
          plugin_stars_limit: 4
